<?php

declare(strict_types=1);

/**
 * This file is part of the Phalcon Kit.
 *
 * (c) Phalcon Kit Team
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace PhalconKit\Mvc\Model\Traits;

use Phalcon\Db\Adapter\AdapterInterface;
use Phalcon\Mvc\Model\Query\Builder;
use PhalconKit\Di\ServiceResolver;
use PhalconKit\Exception\ServiceException;
use PhalconKit\Mvc\Model\ManagerInterface;

/**
 * Provides count helpers for queries that need a subquery wrapper.
 *
 * This is useful when the original find definition contains joins, grouping,
 * or other clauses where a direct model count would not represent the number
 * of result rows correctly. The helper relies on the default PhalconKit DI
 * because it is a static model API.
 */
trait Count
{
    /**
     * Count rows through a subquery generated by the models manager.
     *
     * The supplied find definition is converted to a query builder for the
     * calling model class, compiled to SQL, and wrapped in
     * `SELECT COUNT(*) FROM (...)`. Bind parameters and bind types are reused
     * from the generated query.
     *
     * @param mixed $find Phalcon find parameters accepted by the models manager
     *     builder. Non-array values are wrapped as a single-item parameter
     *     array for compatibility with model find APIs.
     * @return int Total row count reported by the database.
     * @throws ServiceException When the default DI, models manager, or database
     *     service cannot be resolved through the PhalconKit DI contract.
     */
    public static function subCount(mixed $find): int
    {
        $find ??= [];
        $find = is_array($find) ? $find : [$find];
        
        // Get the models manager
        $modelsManager = ServiceResolver::fromDefault(
            'modelsManager',
            ManagerInterface::class,
            context: 'model count helpers'
        );
        
        // Create a builder for the subquery
        $builder = $modelsManager->createBuilder($find)->from(get_called_class());
        
        // Get the raw SQL query and its bind parameters
        $querySql = $builder->getQuery()->getSQL();
        
        // Create the raw SQL query for the count
        $rawSql = "SELECT COUNT(*) AS total_count FROM ({$querySql['sql']}) as query_count";
        
        // Execute the raw SQL query
        $db = ServiceResolver::fromDefault('db', AdapterInterface::class, context: 'model count helpers');
        $result = $db->query($rawSql, $querySql['bind'], $querySql['bindTypes']);
        
        // Fetch the total count
        $row = $result->fetch();
        
        // Return the total count
        return (int)$row['total_count'];
    }
}
