<?php

declare(strict_types=1);

/**
 * This file is part of the Phalcon Kit.
 *
 * (c) Phalcon Kit Team
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace PhalconKit\Mvc\Model\Traits;

use Phalcon\Db\RawValue;
use Phalcon\Mvc\EntityInterface;
use PhalconKit\Encryption\Security;
use PhalconKit\Exception\ServiceException;
use PhalconKit\Mvc\Model\Behavior\Transformable;
use PhalconKit\Mvc\Model\Traits\Abstracts\AbstractBehavior;
use PhalconKit\Mvc\Model\Traits\Abstracts\AbstractInjectable;
use PhalconKit\Mvc\Model\Traits\Abstracts\AbstractOptions;

/**
 * Installs UUID generation behavior for model create operations.
 *
 * The trait supports database-native UUID expressions or UUIDv7 values
 * generated by the configured PhalconKit security service. UUIDs can be stored
 * as strings or packed binary values depending on the model options.
 */
trait Uuid
{
    use AbstractBehavior;
    use AbstractInjectable;
    use AbstractOptions;
    
    /**
     * Initialize the UUID transform behavior for create validation.
     *
     * Options default to the model options manager under `uuid`. Supported
     * keys are:
     *
     * - `field`: target attribute name, default `uuid`
     * - `native`: when true, use database `UUID()` expressions
     * - `binary`: when true, store UUIDs as binary values
     *
     * @param array<string, mixed>|null $options UUID behavior options.
     * @throws ServiceException When the security service cannot be resolved
     *     through the PhalconKit DI contract.
     */
    public function initializeUuid(?array $options = null): void
    {
        $options ??= $this->getOptionsManager()->get('uuid') ?? [];
        
        $field = $options['field'] ?? 'uuid';
        $native = $options['native'] ?? false;
        $binary = $options['binary'] ?? false;
        
        $security = $this->getTypedService('security', Security::class, 'model UUID helpers');
        
        $this->setUuidBehavior(new Transformable([
            'beforeValidationOnCreate' => [
                $field => function (EntityInterface $model, string $field) use ($security, $native, $binary) {
                    return $model->readAttribute($field) ?? $native
                        ? ($binary
                            ? new RawValue('UUID_TO_BIN(UUID())')
                            : new RawValue('UUID()')
                        )
                        : ($binary
                            ? $this->getBinaryUuid($security->getRandom()->uuidv7())
                            : $security->getRandom()->uuidv7()
                        );
                },
            ],
        ]));
    }
    
    /**
     * Convert a canonical UUID string to its packed binary representation.
     *
     * @param string $uuid UUID string with or without hyphens.
     * @return string Binary bytes suitable for binary UUID columns.
     */
    private function getBinaryUuid(string $uuid): string
    {
        return pack('h*', str_replace('-', '', $uuid));
    }
    
    /**
     * Register the UUID transform behavior under the standard behavior name.
     *
     * @param Transformable $uuidBehavior Configured transformable behavior.
     * @throws ServiceException When the current models manager does not expose
     *     the PhalconKit behavior registry.
     */
    public function setUuidBehavior(Transformable $uuidBehavior): void
    {
        $this->setBehavior('uuid', $uuidBehavior);
    }
    
    /**
     * Retrieve the registered UUID transform behavior.
     *
     * @return Transformable Transformable behavior responsible for UUID values.
     * @throws ServiceException When the current models manager does not expose
     *     the PhalconKit behavior registry.
     */
    public function getUuidBehavior(): Transformable
    {
        return $this->getTypedBehavior('uuid', Transformable::class);
    }
}
