-- Core 4.0 fresh-install baseline. References use the selected database.
CREATE TABLE `email` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `template_id` BIGINT UNSIGNED NULL,
    `from` LONGTEXT NOT NULL,
    `reply_to` VARCHAR(255) NULL,
    `return_path` VARCHAR(255) NULL,
    `read_receipt_to` VARCHAR(255) NULL,
    `priority` TINYINT(1) NOT NULL DEFAULT '3',
    `to` LONGTEXT NOT NULL,
    `cc` LONGTEXT NULL,
    `bcc` LONGTEXT NULL,
    `subject` VARCHAR(255) NOT NULL,
    `content` MEDIUMTEXT NOT NULL,
    `meta` LONGTEXT NULL,
    `sent` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `sent_at` DATETIME NULL,
    `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
    `created_by` BIGINT UNSIGNED NULL,
    `updated_at` DATETIME NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `deleted_at` DATETIME NULL,
    `deleted_by` BIGINT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uuid_UNIQUE` (`uuid`),
    KEY `idx_template_id` (`template_id`),
    KEY `fk_email_created_by` (`created_by`),
    KEY `fk_email_updated_by` (`updated_by`),
    KEY `fk_email_deleted_by` (`deleted_by`),
    CONSTRAINT `fk_email_created_by` FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_email_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_email_template_id` FOREIGN KEY (`template_id`) REFERENCES `template`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_email_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
