-- Core 4.0 fresh-install baseline. References use the selected database.
CREATE TABLE `oauth2` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `provider` ENUM('google','microsoft') NOT NULL,
    `provider_uuid` VARCHAR(120) COLLATE utf8mb4_bin NOT NULL,
    `access_token` TEXT COLLATE utf8mb4_bin NOT NULL,
    `refresh_token` TEXT COLLATE utf8mb4_bin NULL,
    `email` VARCHAR(320) NULL,
    `meta` LONGTEXT NULL,
    `deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `created_at` DATETIME NOT NULL DEFAULT current_timestamp(),
    `created_by` BIGINT UNSIGNED NULL,
    `updated_at` DATETIME NULL,
    `updated_by` BIGINT UNSIGNED NULL,
    `deleted_at` DATETIME NULL,
    `deleted_by` BIGINT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uuid_UNIQUE` (`uuid`),
    UNIQUE KEY `provider_uuid_UNIQUE` (`provider_uuid`),
    KEY `idx_user_id` (`user_id`),
    KEY `fk_oauth2_created_by` (`created_by`),
    KEY `fk_oauth2_updated_by` (`updated_by`),
    KEY `fk_oauth2_deleted_by` (`deleted_by`),
    CONSTRAINT `fk_oauth2_created_by` FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_oauth2_deleted_by` FOREIGN KEY (`deleted_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_oauth2_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_oauth2_user_id` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
