<?php

declare(strict_types=1);

/**
 * This file is part of the Phalcon Kit.
 *
 * (c) Phalcon Kit Team
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace PhalconKit\Mvc\Controller\Traits\Actions\Rest;

use Phalcon\Filter\Exception as FilterException;
use Phalcon\Filter\Filter;
use Phalcon\Http\ResponseInterface;
use Phalcon\Mvc\ModelInterface;
use PhalconKit\Exception\LogicException;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractExpose;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractQuery;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractInjectable;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractParams;
use PhalconKit\Mvc\Controller\Traits\Abstracts\AbstractRestResponse;
use PhalconKit\Mvc\Model\Interfaces\PositionInterface;

trait ReorderAction
{
    use AbstractExpose;
    use AbstractQuery;
    use AbstractInjectable;
    use AbstractParams;
    use AbstractRestResponse;
    
    /**
     * Reorder the entity based on the provided position.
     *
     * @return ResponseInterface The response generated by the method.
     * @throws FilterException When request parameter filtering fails.
     * @throws LogicException When the configured model does not support
     *     positional reordering.
     */
    public function reorderAction(): ResponseInterface
    {
        $entity = $this->findFirst();
        
        if (!$entity) {
            return $this->setRestErrorResponse(404);
        }
        
        $position = $this->getParam('position', [Filter::FILTER_INT]);
        
        $entity = $this->requirePositionEntity($entity);
        $reordered = $entity->reorder($position);
        
        $this->view->setVars([
            'reordered' => $reordered,
            'data' => $this->expose($entity),
            'messages' => $entity->getMessages(),
        ]);
        
        return $this->setRestResponse($reordered);
    }

    /**
     * Require the current REST entity to support positional reordering.
     *
     * `reorderAction()` is opt-in controller composition. This helper keeps the
     * action workflow compact while turning a wrong model/controller pairing
     * into a clear PhalconKit logic exception instead of a disabled assertion or
     * late method-call error.
     *
     * @param ModelInterface $entity Entity returned by the query layer.
     *
     * @return ModelInterface&PositionInterface
     *
     * @throws LogicException When the configured model does not support
     *     positional reordering.
     */
    protected function requirePositionEntity(ModelInterface $entity): ModelInterface&PositionInterface
    {
        if ($entity instanceof PositionInterface) {
            return $entity;
        }

        throw new LogicException(sprintf(
            'Configured model "%s" must implement "%s" to use reorderAction().',
            $entity::class,
            PositionInterface::class
        ));
    }
}
