name: OpenSSF Scorecard

on:
  schedule:
    - cron: '35 3 * * 1'
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard-results.json
          results_format: json
          publish_results: true
